# Define the workflow for Continuous Integration for React Native Mobile App
name: Continuous Integration for React Native Mobile App

# Define the name of the run dynamically based on the actor triggering the action
run-name: ${{ github.actor }} is running CI for React Native Mobile App

# Trigger the workflow on pull requests to the main branch
# and only if changes are made in the specified path!
on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/mobile/agapic_health_assistant_app/**'

# Define the jobs to be run as part of this workflow
jobs:
  lint_test_build:
    # Specify the type of runner that the job will execute on
    runs-on: ubuntu-latest

    # Define the sequence of tasks/steps to be executed
    steps:
      - name: Step 1 - Check out the repository code
        uses: actions/checkout@v4
      
      - name: Step 2 - Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Step 3 - Validate the Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Step 4 - Set up the Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Step 5 - Install project dependencies using npm
        run: npm ci
        working-directory: ./frontend/mobile/agapic_health_assistant_app
      
      - name: Step 6 - Run linting on the code
        run: npm run lint
        working-directory: ./frontend/mobile/agapic_health_assistant_app

      - name: Step 7 - Run tests
        run: npm run test
        working-directory: ./frontend/mobile/agapic_health_assistant_app

      - name: Step 8 - Assemble an Android debug build
        run: ./gradlew assembleDebug
        working-directory: ./frontend/mobile/agapic_health_assistant_app/android
