name: Continuous Integration
run-name: ${{ github.actor }} is running Continuous Integration GitHub Actions
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
